version: '3.9'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: wedding-sql
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'DevLocalStr0ng!Pass'
      MSSQL_PID: 'Developer'
    ports:
      - '14333:1433'
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'DevLocalStr0ng!Pass' -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
volumes:
  mssql_data:
    driver: local
