name: Feature Request
description: Propose a new capability or enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: >-
        Ensure proposal aligns with `.github/project_instructions.md` (scope, architecture).
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: e.g. Add responsive typography scale
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation / User Problem
      placeholder: What problem or goal does this solve? Why now?
      validations:
        required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: High-level approach, key components touched, data flows.
      placeholder: |
        - Add ...
        - Refactor ...
        - Consider alternatives ...
      validations:
        required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
  - type: textarea
    id: accessibility
    attributes:
      label: Accessibility Considerations
      placeholder: Focus, semantics, motion, contrast, keyboard, screen reader.
  - type: textarea
    id: performance
    attributes:
      label: Performance Considerations
      placeholder: Bundle impact, lazy-loading, budgets adherence.
  - type: textarea
    id: risks
    attributes:
      label: Risks / Trade-offs
  - type: checkboxes
    id: blueprint
    attributes:
      label: Blueprint Alignment
      options:
        - label: Proposal aligns with project blueprint
          required: true
  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance Criteria
      options:
        - label: Clear success metrics defined
        - label: Testing strategy outlined
