#!/usr/bin/env sh

# Run lint-staged
npx lint-staged --config .lintstagedrc.json

if [ $? -ne 0 ]; then
  echo "Lint-staged failed, aborting commit"
  exit 1
fi

# Stage any changes made by lint-staged
git add .

echo "Staged changes from linting fixes"