name: ChatOps Auto Merge Label

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write

jobs:
  add-label:
    if: >-
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/auto-merge')
    runs-on: ubuntu-latest
    steps:
      - name: Add auto-merge label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: auto-merge
      - name: React to command
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ✅ Applied `auto-merge` label. The auto merge workflow will evaluate gates on next event.
            (Remove the label to cancel.)
