name: coverage-diff

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  coverage-diff:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Run tests with coverage (STRICT a11y headers)
        run: npm run coverage
        env:
          COVERAGE_A11Y_STRICT: '1'
      - name: Compute coverage diff
        run: npm run coverage:diff
      - name: Comment coverage diff
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: coverage-diff.md
      - name: Upload coverage diff artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-diff-artifacts
          path: |
            coverage-diff.md
            coverage-diff.json
      - name: Job summary
        if: always()
        run: |
          echo '## Coverage Diff Summary' >> $GITHUB_STEP_SUMMARY
          if [ -f coverage-diff.md ]; then
            cat coverage-diff.md >> $GITHUB_STEP_SUMMARY
          else
            echo 'coverage-diff.md missing' >> $GITHUB_STEP_SUMMARY
          fi
