name: CI - Coverage Badge

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  workflow_dispatch: {}

concurrency:
  group: coverage-badge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  badge:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Cache Vitest & Vite
        uses: actions/cache@v4
        with:
          path: |
            .vitest
            node_modules/.cache/vite
          key: vitest-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            vitest-${{ runner.os }}-${{ matrix.node-version }}-
      - name: Run tests with coverage (STRICT a11y headers)
        run: npm run coverage
        env:
          COVERAGE_A11Y_STRICT: '1'
      - name: Upload coverage directory
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node-version }}
          path: coverage
          if-no-files-found: error
  aggregate:
    needs: badge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Cache Vitest & Vite
        uses: actions/cache@v4
        with:
          path: |
            .vitest
            node_modules/.cache/vite
          key: vitest-${{ runner.os }}-aggregate-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            vitest-${{ runner.os }}-aggregate-
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: coverage-artifacts
      - name: Arrange coverage summaries
        run: |
          mkdir -p coverage-matrix
          for d in coverage-artifacts/*; do
            if [ -d "$d" ] && [ -f "$d/coverage-summary.json" ]; then
              name=$(basename "$d")
              mkdir -p "coverage-matrix/$name"
              cp "$d/coverage-summary.json" "coverage-matrix/$name/coverage-summary.json"
            fi
          done
          echo "Aggregating summaries:" && ls -R coverage-matrix || true
      - name: Aggregate coverage
        run: npm run coverage:aggregate
      - name: Generate coverage badge
        run: |
          npm run coverage:badge
          ls -al .github/badges
      - name: Commit badge
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .github/badges/coverage.svg
          git diff --cached --quiet && echo "No badge changes" && exit 0
          git commit -m "chore(ci): update aggregated coverage badge" || echo "No changes"
          git push
