name: Curated Triage

on:
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC
  workflow_dispatch: {}
  push: {}

jobs:
  run-curated-scans:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup PowerShell
        uses: actions/setup-pwsh@v2

      - name: Install dependencies
        run: |
          python -m pip install --user git-filter-repo
        shell: bash

      - name: Run entropy scan (PowerShell)
        run: pwsh -c "./scripts/entropy-scan.ps1 -MinLen 40 -Base64EntropyThreshold 4.6 -HexEntropyThreshold 3.9 -MaxMatches 500 -OutFile security-scans/curated/high-confidence-ci.txt"

      - name: Generate curated triage (PowerShell)
        run: pwsh -c "./scripts/generate-curated-triage.ps1 -MaxSamplesPerPattern 5 -ScansDir security-scans -OutDir security-scans/curated"

      - name: Upload curated artifacts
        uses: actions/upload-artifact@v4
        with:
          name: curated-triage-outputs
          path: |
            security-scans/curated/triage-summary.csv
            security-scans/curated/high-confidence-ci.txt
            security-scans/curated/samples/**
            audit-report.txt

  release-on-demand:
    runs-on: ubuntu-latest
    needs: run-curated-scans
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release (draft)
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: triage-artifacts-latest-${{ github.run_id }}
          name: "Triage artifacts (manual) ${{ github.run_id }}"
          body: |-
            Curated triage artifacts and audit report produced by scheduled/dispatch run.
            Use this release to store curated artifacts that are safe to review.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v1
        with:
          files: "security-scans/curated/triage-summary.csv,security-scans/curated/high-confidence-ci.txt,audit-report.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
