name: issue-auto-label

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch issue
        id: fetch
        uses: actions-ecosystem/action-get-issue@v1
      - name: Auto-label via title & template heuristics
        id: auto
        run: |
          set -e
          body=$(jq -r '.body' <<< '${{ toJson(steps.fetch.outputs) }}' || echo '')
          title='${{ steps.fetch.outputs.title }}'
          labels=()
          shopt -s nocasematch || true
          if [[ $title == *bug* ]] || grep -qi '### Expected Behavior' <<< "$body"; then
            labels+=("type:bug")
          fi
          if [[ $title == *feature* ]] || grep -qi '### Feature Description' <<< "$body"; then
            labels+=("type:feature")
          fi
          if [[ $title == *task* ]] || grep -qi '### Task Description' <<< "$body"; then
            labels+=("type:task")
          fi
          shopt -u nocasematch || true
          if [ ${#labels[@]} -eq 0 ]; then
            echo 'No label heuristics matched.'
            exit 0
          fi
          printf 'Labels to add: %s\n' "${labels[*]}"
          echo "labels=${labels[*]}" >> $GITHUB_OUTPUT
      - name: Add labels (API)
        if: steps.auto.outcome == 'success'
        run: |
          labels='${{ steps.auto.outputs.labels }}'
          if [ -z "$labels" ]; then echo 'No labels to apply'; exit 0; fi
          for lbl in $labels; do
            echo "Applying $lbl"
            gh issue edit ${{ github.event.issue.number }} --add-label "$lbl"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
