name: Docs - Markdown Lint

on:
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.*'
  push:
    branches: [main]
    paths:
      - '**/*.md'
      - '.markdownlint.*'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install markdownlint-cli
        run: npm install --no-save markdownlint-cli@0.41.0
      - name: Run markdownlint
        run: npx markdownlint '**/*.md' -c .markdownlint.jsonc || (echo "::error::Markdown lint failed. Run npx markdownlint '**/*.md' locally." && exit 1)
