name: post-deploy-lighthouse
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: read
  actions: read

jobs:
  lh-audit:
    runs-on: ubuntu-latest
    env:
      PROD_URL: ${{ secrets.PROD_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Run Lighthouse CI (production)
        if: env.PROD_URL != ''
        run: |
          npx lhci autorun --collect.url=$PROD_URL --config=lighthouserc.json || echo "Lighthouse run completed with non-blocking issues"
      - name: Warn missing PROD_URL
        if: env.PROD_URL == ''
        run: echo "PROD_URL secret not set; skipping Lighthouse audit"
