name: Sample PR Seeder

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps (prod only)
        run: npm ci --omit=dev
      - name: Check existing sample history
        id: hist
        run: |
          if [ -f artifacts/quality-history.jsonl ]; then COUNT=$(wc -l < artifacts/quality-history.jsonl); else COUNT=0; fi
          echo "history_lines=$COUNT" >> $GITHUB_OUTPUT
      - name: Abort if enough samples
        if: ${{ steps.hist.outputs.history_lines != '' && steps.hist.outputs.history_lines >= 10 }}
        run: echo "History has >=10 samples; skipping seeding run." && exit 0
      - name: Configure git user
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@users.noreply.github.com'
      - name: Create sample PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/create_sample_pr.mjs
