name: Validate TODO Exclusions

on:
  pull_request:
    paths:
      - '.vscode/settings.json'
      - '.github/workflows/validate_todo_exclusions.yml'
      - 'docs/accessibility_performance_plan.md'
  push:
    branches: [main]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify exclusion globs
        run: |
          FILE='.vscode/settings.json'
          required=(
            '**/docs/self_review_checklist.md'
            '**/.github/pull_request_template.md'
            '**/.github/ISSUE_TEMPLATE/**'
            '**/.github/project_instructions.md'
            '**/CHANGELOG.md'
            '**/coverage/**'
            '**/CONTRIBUTING.md'
            '**/lighthouse/**'
            '**/docs/accessibility_performance_plan.md'
          )
          missing=0
          for pattern in "${required[@]}"; do
            if ! grep -Fq "$pattern" "$FILE"; then
              echo "Missing exclusion pattern: $pattern" >&2
              missing=1
            fi
          done
          if [ $missing -ne 0 ]; then
            echo 'One or more required exclusion globs are missing.' >&2
            exit 1
          fi
          echo 'All required exclusion globs present.'
